// Onboarding hooks
export * from "./onboarding";

// API hooks are exported separately to avoid conflicts
export {
  useLogin,
  useLogout,
  useCurrentUser,
  useCreateOrganization as useCreateOrganizationApi,
  useCreateOrganizationConfig,
  useOrganizationConfigAdmin,
  useRegister as useRegisterApi,
  useVerifyEmail as useVerifyEmailApi,
  useSetPassword as useSetPasswordApi,
  useResendVerification,
  useAuth,
  useGetAllUsers,
  useDeleteUser,
  useInviteTeacher,
  useInviteAdmin,
  useGetAllBatches,
  useGetBatch,
  useGetBatchReviewsAdmin,
  useGetCategories,
  useGetAnnouncements,
  useCreateBatch,
  useCreateCategory,
  useCreateAnnouncement,
  useUpdateCategory,
  useUpdateBatch,
  useUpdateBatchCertificateConfig,
  useDeleteBatch,
  useDeleteCategory,
  useCreateTeacher,
  useGetAllTeachers,
  useGetTeachersByBatch,
  useUpdateTeacher,
  useDeleteTeacher,
  useAssignTeacherToBatch,
  useRemoveTeacherFromBatch,
  useGenerateSignedUrl,
  useDirectUpload,
  useCreateSubject,
  useGetSubjectsByBatch,
  useGetCourseHierarchy,
  useGetClientCourseHierarchy,
  useGetChaptersByBatch,
  useGetCourseOutline,
  useGetClientChaptersByBatch,
  useGetClientCourseOutline,
  useGetSubject,
  useUpdateSubject,
  useDeleteSubject,
  useCreateChapter,
  useGetChaptersBySubject,
  useGetChapter,
  useUpdateChapter,
  useDeleteChapter,
  useCreateTopic,
  useGetTopicsByChapter,
  useGetTopic,
  useUpdateTopic,
  useUpdateTopicQuiz,
  useDeleteTopicQuiz,
  useSubmitTopicQuizAttempt,
  useDeleteTopic,
  useCreateContent,
  useGetContentsByTopic,
  useGetContent,
  useUpdateContent,
  useDeleteContent,
  useReorderContents,
  useGetAssignments,
  useGetAssignment,
  useCreateAssignment,
  useUpdateAssignment,
  useDeleteAssignment,
  useCreateAssignmentQuestion,
  useGenerateAssignmentWithAi,
  useUpdateAssignmentQuestion,
  useDeleteAssignmentQuestion,
  useGetAssignmentSubmissions,
  useGetAssignmentAnalytics,
  useGradeAssignmentSubmission,
  usePublishAssignmentSubmission,
  useGetStudentAssignment,
  useSubmitAssignment,
  useSaveAssignmentDraft,
  useGetExploreBatches,
  useGetExploreBatch,
  useGetBatchCertificateStatus,
  useClaimBatchCertificate,
  useCreateBatchReview,
  useGetMyBatches,
  useGetBatchSchedules,
  useCreateBatchCheckout,
  useVerifyBatchPayment,
  useEnrollFreeBatch,
  useGetExploreTestSeries,
  useGetExploreTestSeriesById,
  useGetClientSubjectsByBatch,
  useGetClientSubject,
  useGetClientChaptersBySubject,
  useGetClientChapter,
  useGetClientTopicsByChapter,
  useGetClientTopic,
  useGetClientContentsByTopic,
  useGetClientContent,
  useProfile,
  useUpdateProfile,
  useOrderHistory,
  useGetOrderById,
  useCreateCourseOrderCheckout,
  useUploadOrderProof,
  useAdminOrders,
  useAdminOrderById,
  useApproveAdminOrder,
  useRejectAdminOrder,
  useClientGenerateSignedUrl,
  useClientDirectUpload,
  useAiChat,
  useTeacherGeneratePlayground,
  useGetBatchPlaygrounds,
  useGetPlaygroundById,
  usePublishPlaygroundToTopic,
  useGetWeakConcepts,
  queryKeys,
} from "./api";

// Dashboard hooks
export * from "./dashboard";

// Authentication hooks
export * from "./auth";

// Common hooks
export * from "./common";

// Test Series hooks
export * from "./test-series";
export * from "./test-series-client";
export * from "./test-attempts-client";
export * from "./tests-client";

// Schedule hooks
export * from "./schedules";

// Client Schedule hooks
export * from "./schedules-client";
