name: Trigger auto deployment for teslabackend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ skipaionboarding ]
    paths:
    - '**'
    - '.github/workflows/teslabackend-AutoDeployTrigger-d9a35ee1-6b3e-49f2-8c6b-d48d0a6b1573.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TESLABACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESLABACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESLABACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.TESLABACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESLABACKEND_REGISTRY_PASSWORD }}
          containerAppName: teslabackend
          resourceGroup: tesla_rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


